### ISSUE TITLE
Creating Hardware Capability Viewer version for iOS?

### ISSUE THREAD

**Issue by KarenGhavam-lunarG** [SaschaWillems/VulkanCapsViewer#103]
Would it be possible to create a version of the Hardware Capability Viewer to be run on iOS devices?

**Comment by richard-lunarg** [comment]
I have a couple of things to add to this.

It would also be really great if it could run vulkaninfo to get the portability .json file and add that to the database as well. There is already a PR in progress to run vulkaninfo on iOS here:

https://github.com/KhronosGroup/Vulkan-Tools/pull/476

Most of the above project is just the iOS "container" application. If VK_USE_PLATFORM_IOS_MVK is defined, it changes main() in vulkaninfo.cpp to:
int vulkanInfoMain(int argc, char **argv)

And you can just call this function to invoke vulkaninfo, and all json files are output to the apps shared files directory. For example:

const char *jsonArgs[2] = { "vulkaninfo", "--json" };
vulkanInfoMain(2, (char **)jsonArgs);

or

const char *portArgs[2] = { "vulkaninfo", "--portability" };
vulkanInfoMain(2, (char **)portArgs);

Another fly in the ointment is that I tried to publish the iOS version of vulkaninfo on the Apple app store so developers would not have to build it themselves. It was rejected on the grounds that it did not provide enough "utility or entertainment value."

Your tool on iOS may have the same response, although I hardly see how the "OpenGL Extension viewer", which has been available for years adds a great deal more value than an app that spells out Vulkan capabilities, unless the benchmark or database features help.

If this is something you're interested in, then let me know if I can help with this, or if you don't have time to work on this yourself. I'm also very familiar with Qt (going back to version 3.0 actually).

**Comment by SaschaWillems** [comment]
### On iOS support

Adding iOS support shouldn't be that much of a problem. I know that people already did this on their own, and there are already iOS devices listed in the database, see e.g. https://vulkan.gpuinfo.org/displayreport.php?id=2664

MacOS support is already in, and iOS support is mostly WSI and project setup. It was briefly discussed in https://github.com/SaschaWillems/VulkanCapsViewer/issues/45, so maybe we can reopen that discussion.

@richard-lunarg  Any help, e.g. a PR would be appreciated, as I don't own any Apple device to actually develop and test. I also don't own a Apple developer account, so it would probably not make it to the store.

I'll also ping @oscarbg so he may chime in on the discussion. He submitted the above iOS report and may be able to help :)

### On uploading reports from vulkaninfo

The database does not store portability JSON files directly. They are generated at runtime via an api. So in order to get reports from e.g. vulkaninfo into the database, that tool would have to generate reports in the same form as The Vulkan Caps Viewer. As that format is more-or-less tightly coupled to the application, that would require a synchronization between these two projects.

So I'm not sure if that's feasible, and if we can get iOS support into the Vulkan Caps Viewer, there would be no need to add this anyway.

**Comment by SaschaWillems** [comment]
See PR #110
