### ISSUE TITLE
False positive for device already in database

### ISSUE THREAD

**Issue by AlessandroBorges** [SaschaWillems/VulkanCapsViewer#18]
Hi,Sascha

I'd like to report that current version report a false positive for device already in database.
I guess its using only deviceID / VendorID  and, possibly,  driverversion. I guess AMD is using same values for several cards. 
Attached is my AMD R7 240 (Gigabyte)  json report, with different values when compared to current one available at database ( http://vulkan.gpuinfo.org/displayreport.php?id=219 ) , but Vulkan Cap viewer insists that is the same one already in database. It is a false positive report.
I'd like to suggest using another keys to compare reports. Maybe a 32 bit hash code from entire json report.
[vulkanreport.json.txt](https://github.com/SaschaWillems/VulkanCapsViewer/files/237736/vulkanreport.json.txt)

**Comment by SaschaWillems** [comment]
Thanks for the issue. I'm not 100% sure with the way reports are checked against the database, so I'm going to do something anyway.

A complete hash is not an option as it would cause duplicate reports if I add new values to the database and reports.

DeviceIDs and names for AMD are based on the GPU series (e.g. R7 200 series) and contrary to e.g. NVIDIA.

But the main culprit is the fact that they haven't updated the driver version since the first beta driver. I expect this to change once the Vulkan drivers gets out of beta.

**Comment by AlessandroBorges** [comment]
Just a idea - add **apiversion** and **architecture** in the compound database key.
From my report and the another one already in database the apiversion are different : 1.0.8 and 1.0.3, respec.
But in case  of same driver versions, it may has different OS arch.

**Comment by SaschaWillems** [comment]
Comparing against the apiversion will be added (hopefully this weekend), but I'd also like to have newer AMD drivers have newer version strings too ;)

**Comment by SaschaWillems** [comment]
AMD is now updating the Vulkan version for each driver, so this should work fine now. Will add the check against the apiversion in a future release.
