### ISSUE TITLE
Error at instance layer when trying to upload report

### ISSUE THREAD

**Issue by MacGamerFR** [SaschaWillems/VulkanCapsViewer#74]
![Capture d’écran_2019-07-18_13-35-32](https://user-images.githubusercontent.com/8853392/61454350-f2626500-a960-11e9-84a0-6d098b05004a.png)
On Archlinux, with AUR package v1.93, I get this error while trying to upload a report.
All Vulkan's packages installed:
- vulkan-devel package group including (non exhaustive) :
  - vulkan-extra-layers 1.1.97.0+10340+118b2f331-1
  - vulkan-icd-loader 1.1.115-1
  - vulkan-validation-layers 1.1.107-1
- nvidia-utils 430.34-1 (NVidia vulkan driver)

Last and only report made with the same machine: https://vulkan.gpuinfo.org/displayreport.php?id=5352

Regards

**Comment by SaschaWillems** [comment]
Can you please try to upload again?

The error was caused by a duplicate primary key. Looking at the report it seems that the ```VK_LAYER_NV_nomad``` is present twice, which caused a primary key database violation.

I have changed the upload code to ignore these, so uploading should no longer fail in such case.

But you may also want to check why that layer is reported twice on your setup.

**Comment by MacGamerFR** [comment]
It worked, thanks !

About this layer, I have `VK_LAYER_NV_nomad` and `VK_LAYER_NV_nomad_release_public_2019_3_1` and I suppose it is from Nvidia NSight Graphics installed on the computer (two times, it can be the source of the "problem")

**Comment by MacGamerFR** [comment]
It was because there was two times the layer JSON file: one in `/usr/share/vulkan/implicit_layer.d/` and one in `~/.local/share/vulkan/implicit_layer.d`

I deleted them, no more two entries :smile:
